# Generated by Django 4.0.1 on 2022-05-24 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_builderApp', '0002_academics_areaofinterest_education_person_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Academics',
            new_name='Academic',
        ),
        migrations.RenameModel(
            old_name='ProfessionalSkills',
            new_name='ProfessionalSkill',
        ),
    ]
